### PR TITLE
Join names

### PR DESCRIPTION
**Pull request by llllllllll**
sqlalchemy was raising warnings and you couldn't actually access the left and right sides any more.

### CODE REVIEW

**Comment by llllllllll** [comment]
looks like dask is complaining about some stuff, did anything change here recently?

**Comment by cpcloud** [comment]
dask is changing fairly rapidly these days

ping @mrocklin

**Comment by cpcloud** [comment]
ok this dask stuff is blocking, taking care of it now

**Comment by cpcloud** [comment]
very small issue .... going to push directly to master

**Comment by cpcloud** [comment]
fixed in 376d87b

**Comment by cpcloud** [comment]
sorry ... your whatsnew conflicts with the one i just merged in :|

**Comment by llllllllll** [comment]
rebased, does the change look correct, if so I will merge on pass.

**Pull request merged**
