### PR TITLE
Try to import cytoolz and fallback to toolz

### LINKED ISSUE #1036: cytoolz is required to import blaze, but it's not listed in requirements_strict.txt
In a fresh virtualenv, `pip install blaze && python -c "import blaze"` fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssanderson/.virtualenvs/blaze/local/lib/python2.7/site-packages/blaze/__init__.py", line 18, in <module>
    from .utils import ignoring
  File "/home/ssanderson/.virtualenvs/blaze/local/lib/python2.7/site-packages/blaze/utils.py", line 7, in <module>
    from cytoolz import nth
ImportError: No module named cytoolz
```

Is there a reason cytoolz isn't in the strict requirements if it's necessary to even import the top-level module?

### PR DESCRIPTION
**Pull request by cpcloud**
closes #1036

### CODE REVIEW

**Comment by cpcloud** [comment]
@ssanderson can you test that this fixes the issue?

**Comment by cpcloud** [comment]
i don't the have connection bandwidth ATM to install numpy wheels etc.

**Comment by ssanderson** [comment]
@cpcloud LGTM.  How important is using cytoolz for performance compared to vanilla toolz?  Is it worth throwing a warning if the user doesn't have cytoolz?

**Comment by mrocklin** [comment]
This is really just for the streaming python backend, which doesn't get much use nowadays.  We probably don't care about cytoolz performance here.  A lot of this is moving to dask.bag anyway.

**Comment by ssanderson** [comment]
@mrocklin sounds good.

**Pull request merged**
