### PR TITLE
allow blaze client to disable ssl verification

### PR DESCRIPTION
**Pull request by llllllllll**
verifies the cert by default; however, we want to disable this

Side note: we might want to think about making ssl the default. There is no downside really and it helps people who might not have thought about the fact that they will be streaming potentially sensitive data over the interned.

note: wait for #1172 and then change the .get to .post

### CODE REVIEW

**Comment by cpcloud** [comment]
> we might want to think about making ssl the default.

isn't that what you've implemented here?

**Comment by cpcloud** [comment]
or do you mean use `https://` by default?

**Comment by llllllllll** [comment]
> or do you mean use https:// by default?

yeah, this just makes it so that if it uses ssl with a custom cert that it doesn't check the cert. I imagine most production setups will want to serve their data with https.

**Comment by cpcloud** [comment]
@llllllllll this can be merged after fixing up conflicts and passing

**Pull request merged**
