### PR TITLE
Rosetta stone for blaze <-> pandas

### LINKED ISSUE #888: Pandas-Blaze Rosetta stone
It would be great to have a doc that translated between Pandas and Blaze API.  A few simple examples here would probably go a long way.

### PR DESCRIPTION
**Pull request by cpcloud**
closes #888

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks great.  Some suggestions after first glance

1.  Code highlighting 
2.  Use same variable name on both sides rather than `df` and `t`. 
3.  Mention `into`, perhaps with `read_csv`, `to_csv`, `from_sql` as example operations on the Pandas side

**Comment by cpcloud** [comment]
So, I'd rather drink battery acid than make another table with reStructuredText.

**Comment by cpcloud** [comment]
got 1 and 2 down, adding the into examples now

**Comment by mrocklin** [comment]
Ha!  Maybe raw HTML?  Although I guess code highlighting becomes less fun.

**Comment by cpcloud** [comment]
@mrocklin i've addressed 1-3, i think this is good to go

**Comment by mrocklin** [comment]
I've issued a PR to your branch here https://github.com/cpcloud/blaze/pull/4

**Comment by cpcloud** [comment]
@mrocklin any more comments here?

**Comment by mrocklin** [comment]
Only that I shouldn't have held up documentation.  I think that this is a really useful document.

**Comment by cpcloud** [comment]
no problemo, bombs away on green

**Pull request merged**
