### PR TITLE
add dummy type for pymongo.Database

### PR DESCRIPTION
**Pull request by mrocklin**
This was killing doc builds

### CODE REVIEW

**Comment by cpcloud** [comment]
`pytest 2.7.0` was release recently ... should we start removing the dummy hacks?

**Comment by cpcloud** [comment]
also thanks for monitoring the doc builds

**Comment by mrocklin** [comment]
> pytest 2.7.0 was released recently ... should we start removing the dummy hacks?

Sounds fine to me.

**Comment by mrocklin** [comment]
Merging when tests pass

**Comment by cpcloud** [comment]
Cool

**Pull request merged**
