### PR TITLE
Only allow POST requests on compute.<format> route

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by llllllllll** [comment]
Not sure what the conda stuff is for, but the `post` change looks good to me.

Do we need to worry about how this will affect bokeh integration?

**Comment by cpcloud** [comment]
conda stuff was an accident i branched off the wrong branch

**Comment by cpcloud** [comment]
cc @bryevdv @fpliger are you guys ok with this change?

**Comment by bryevdv** [comment]
Looks like the `BlazeDataSource` already uses `POST`:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/source/blaze_data_source.coffee#L31

So should hopefully be ok?

**Comment by fpliger** [comment]
> Looks like the BlazeDataSource already uses POST:

ah, right. This looks like a safe change.. we can pay particular attention to that and test

**Comment by cpcloud** [comment]
thanks for the comments guys. merging

**Pull request merged**
