### PR TITLE
Update to use odo

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@mrocklin this could your review whenever you get a chance.

**Comment by mrocklin** [comment]
How about build requirements in requirements.txt and the conda recipes?  Should we wait on this until things like anaconda are updated?

**Comment by cpcloud** [comment]
ah right

**Comment by mrocklin** [comment]
There is also no need to rush this.  Into is still around.

**Comment by cpcloud** [comment]
i kind of wanted to get everything synced up all at once for projects that depend on blaze and into

**Comment by jreback** [comment]
my 2c I would make this change in say blaze 0.8
eg s major version change

**Comment by cpcloud** [comment]
hm ok

**Comment by cpcloud** [comment]
@jreback @mrocklin i'm going to kick up some dust with this here PR. marked this for 0.8.0 and will tag as such when said dust has settled

**Comment by mrocklin** [comment]
Sounds fine to me.  Merge at will.

**Pull request merged**
