### PR TITLE
Blueprint registration

### PR DESCRIPTION
**Pull request by llllllllll**
Looking back at the blueprint change I made; I don't think it made it much easier to actually pull the endpoints into another app because of how I did the data registration. This change makes it so that registering the api blueprint adds both the endpoints and the data itself so that it is a single step. This also updates the docs to show the corrected usage.

This makes it much easier to take these endpoints and put them on an app that you want to feed into gunicorn or something.

### CODE REVIEW

**Comment by llllllllll** [comment]
Any idea why that one test died only on py2.7 with spark 1.2? Transient error?

**Comment by cpcloud** [comment]
yep, just rehash and push to restart the build

```sh
git commit --amend -C HEAD && git push --force
```

**Comment by mrocklin** [comment]
travis.ci also has a restart button

**Comment by llllllllll** [comment]
Where is the restart button, or is it only available to repo owners/collaborators?

**Comment by cpcloud** [comment]
There's nothing wrong with rehashing the commit and then force pushing. Additionally, @llllllllll rehashing and pushing doesn't depend on you having access rights to the travis build.

**Comment by cowlicks** [comment]
@llllllllll Closing and reopening the PR will also trigger a re-test. In case you don't want to sign in/register with travis-ci.

**Comment by llllllllll** [comment]
Oh, I already have an account with travis; however, idk how to do restart a test in their UI.

**Comment by cpcloud** [comment]
looks good to me, merging

**Comment by llllllllll** [comment]
Thanks

**Pull request merged**
