### PR TITLE
run Travis CI on docker container

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by mrocklin** [comment]
What are the benefits to this?

**Comment by talumbau** [comment]
this is an experiment to see if docker-based Travis CI starts builds significantly faster than standard Travis CI (as has been claimed). if this is true and it's a one line change, seems reasonable to change.

**Comment by mrocklin** [comment]
Sure.  Lets see how travis responds

**Comment by talumbau** [comment]
Also, the docker builds support a caching feature, which might be useful given that we pip install quite a few things:

http://docs.travis-ci.com/user/caching/

We are not forced to use this, but it is supported.

**Comment by mrocklin** [comment]
We just got these times for travis.  Going to hit the restart button

```
Build Matrix
Job	Duration	Finished	Python	OS
 2982.1	3 min 33 sec	8 minutes ago	2.6	linux
 2982.2	2 min 35 sec	4 minutes ago	2.7	linux
 2982.3	2 min 55 sec	2 minutes ago	3.3	linux
 2982.4	3 min 15 sec	less than a minute ago	3.4	linux
```

**Comment by mrocklin** [comment]
Second run

```
	Duration	Finished	Python	OS
 2982.1	3 min 41 sec	30 minutes ago	2.6	linux
 2982.2	2 min 29 sec	31 minutes ago	2.7	linux
 2982.3	3 min 45 sec	27 minutes ago	3.3	linux
 2982.4	3 min 34 sec	26 minutes ago	3.4	linux
```

And two runs from before this PR

https://travis-ci.org/ContinuumIO/blaze/builds/48520332
```
Job	Duration	Finished	Python	OS
 2980.1	5 min 57 sec	about 22 hours ago	2.6	linux
 2980.2	3 min 14 sec	about 22 hours ago	2.7	linux
 2980.3	5 min 16 sec	about 22 hours ago	3.3	linux
 2980.4	5 min 33 sec	about 22 hours ago	3.4	linux
```

https://travis-ci.org/ContinuumIO/blaze/builds/48416117
```
Build Matrix
Job	Duration	Finished	Python	OS
 2978.1	4 min 58 sec	a day ago	2.6	linux
 2978.2	3 min 1 sec	a day ago	2.7	linux
 2978.3	4 min 35 sec	a day ago	3.3	linux
 2978.4	5 min 17 sec	a day ago	3.4	linux
```

Looks like a significant speedup

**Pull request merged**
