### PR TITLE
Fix naming of reductions when using a generated leaf from the compute sequence

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by llllllllll** [comment]
Was the old name: `__sum`?

**Comment by cpcloud** [comment]
yes

**Comment by cpcloud** [comment]
while that's a valid python identifier, not all system accept this, moreover it exposes an implementation detail

**Comment by llllllllll** [comment]
Gotcha, this looks good then. Want to put an entry in whatsnew to mention the fix?

**Comment by cpcloud** [comment]
ah! thanks for reminding me

**Comment by cpcloud** [comment]
merging on pass

**Pull request merged**
